name: Generate Release Note

on:
  push:
    branches:
      - 'release/**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your project
        uses: actions/checkout@v2

      # - name: Release
      #   uses: fregante/release-with-changelog@v3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     template: '{commits}'

      - name: Release
        uses: ph-fritsche/action-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
