name: Generate Release Note

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create an incremental release
      uses: aurestic/incrementarl-create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    # - uses: fregante/release-with-changelog@v3
    #   with:
    #     template: '{commits}'
    #     token: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Create Release Note
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      # with:
      #   disable-autolabeler: true

    # - name: Create Release
    #   id: semrel
    #   uses: go-semantic-release/action@v1
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
