name: Generate Release Note

on:
  push:
    branches:
      - 'release/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create an incremental release
      uses: aurestic/incrementarl-create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    # - uses: fregante/release-with-changelog@v3
    #   with:
    #     template: '{commits}'
    #     token: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Create Release
      id: semrel
      uses: go-semantic-release/action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}