name: Generate Release Note

on:
  push:
    branches:
      - 'release/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Semantic Releaser
      uses: jossef/action-semantic-releaser@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
